apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-mysql-pvc
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-wwwroot-pvc
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-appdata-pvc
spec:
  storageClassName: local-path
