apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forum-ingress
  annotations:
    cert-manager.io/cluster-issuer: wetfish-letsencrypt
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - testforum.wetfish.net
    secretName: forum-tls
  rules:
  - host: testforum.wetfish.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forum-web
            port:
              number: 80
